version: "3.3"
services:
  postgres:
    image: "postgres:9.6"
    container_name: "postgres"
    restart: "always"
    ports: 
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=mypassword
    hostname: "172.17.0.1"
#  library:
#    image: "library:latest"
#    depends_on:
#      - postgres
#    ports:
#      - "8181:8181"
#    environment:
#      - LIBRARY_DBCONN=postgres://postgres:mypassword@postgres:5432/postgres?sslmode=disable
#      - LIBRARY_PORT=8181
